version: '3'
services:
  movies:
    image: sandeepvmds/moviespaytmrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: sandeepvmds/trainpaytmrepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: sandeepvmds/dthpaytmrepo:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: sandeepvmds/moviespaytmrepo:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
